# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define :attacker do |attacker|
      attacker.vm.box = "ubuntu/focal64"
      attacker.vm.network :private_network, ip: "192.168.56.100"
      attacker.vm.hostname = "attacker"
      attacker.vm.synced_folder "scripts/", "/home/vagrant/scripts"
      attacker.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
      end
      attacker.vm.provision 'shell', inline: <<-SHELL
        echo 'ubuntu:ubuntu' | sudo chpasswd
      SHELL
    end
  
    config.vm.define :server do |server|
      server.vm.box = "ubuntu/focal64"
      server.vm.network :private_network, ip: "192.168.56.101"
      server.vm.hostname = "server"
      server.vm.synced_folder "scripts/", "/home/vagrant/scripts"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
      end
      server.vm.provision 'shell', inline: <<-SHELL
        echo 'ubuntu:ubuntu' | sudo chpasswd
      SHELL
    end

    config.vm.define :client do |client|
        client.vm.box = "ubuntu/focal64"
        client.vm.network :private_network, ip: "192.168.56.102"
        client.vm.hostname = "client"
        client.vm.synced_folder "scripts/", "/home/vagrant/scripts"
        client.vm.provider "virtualbox" do |vb|
          vb.memory = 1024
        end
        client.vm.provision 'shell', inline: <<-SHELL
          echo 'ubuntu:ubuntu' | sudo chpasswd
        SHELL
      end
  end